import { Inter } from "next/font/google";
import '../styles/globals.css'
import Header from "./(landing)/_components/Header";
import Footer from "./(landing)/_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="">
            {children}
          </main>
           <Footer/>
        </div>
      </body>
    </html>
  );
}
